[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# publish "." would otherwise serve these as static files
[[redirects]]
  from = "/netlify/*"
  to = "/index.html"
  status = 404
  force = true

[[redirects]]
  from = "/node_modules/*"
  to = "/index.html"
  status = 404
  force = true
